Repository hassio-addons/addon-ssh, pull requests merged in 2021-02, with the labels that each got.

#189 Upgrade add-on base image to 9.1.1
  ssh/Dockerfile
  ssh/build.json
Labels: dependencies, major

#190 Upgrade ttyd 1.6.3 & libwebsockets 4.1.4
  ssh/Dockerfile
Labels: dependencies

#191 Allow dependabot to upgrade Python dependencies
  .github/dependabot.yaml
Labels: maintenance

#171 Disable SSH DNS lookup
  ssh/rootfs/etc/ssh/sshd_config
Labels: enhancement

#176 Update link and copy in README
  README.md
Labels: documentation

#177 Update link and copy in DOCS
  ssh/DOCS.md
Labels: documentation

#194 :arrow_up: Upgrades Home Assistant CLI to v4.10.0
  ssh/Dockerfile
  ssh/rootfs/etc/motd
  ssh/rootfs/etc/profile.d/show_motd.sh
Labels: dependencies, enhancement

#195 Upgrade add-on base image to 9.1.2
  ssh/Dockerfile
  ssh/build.json
Labels: dependencies

#199 :arrow_up: Upgrades docker to 20.10.3-r0
  ssh/Dockerfile
Labels: dependencies

#200 :arrow_up: Upgrades Home Assistant CLI to v4.10.1
  ssh/Dockerfile
Labels: dependencies

#202 Update add-on configuration for Supervisor 2021.2
  .github/workflows/ci.yaml
  ssh/config.json
Labels: maintenance

#203 :arrow_up: Upgrades git to 2.30.1-r0
  ssh/Dockerfile
Labels: dependencies

#209 Upgrade add-on base image to 9.1.4
  ssh/Dockerfile
  ssh/build.json
Labels: dependencies

#206 Fix/Remove broken documentation link
  ssh/.README.j2
Labels: documentation

#210 Remove full access parameter
  ssh/config.json
Labels: refactor

#213 :arrow_up: Upgrades python3 to 3.8.7-r1
  ssh/Dockerfile
Labels: dependencies
