Repository hassio-addons/addon-ssh, pull requests merged in 2021-12, with the labels that each got.

#346 Fix privileged mode instructions for HASS 2021.12
  ssh/rootfs/usr/local/bin/docker
Labels: documentation

#347 Update CI Workflows
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#348 ⬆️ Upgrades add-on base image to 11.0.0
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies, major

#349 🔥 Remove STDIN service
  ssh/DOCS.md
  ssh/config.yaml
  ssh/rootfs/etc/services.d/stdin/finish
  ssh/rootfs/etc/services.d/stdin/run
Labels: breaking-change

#350 🔥 Remove hibp checks
  README.md
  ssh/.README.j2
  ssh/DOCS.md
  ssh/config.yaml
  ssh/rootfs/etc/cont-init.d/ssh.sh
Labels: breaking-change

#351 ⬆️ Upgrades ttyd to 3e37e33
  ssh/Dockerfile
Labels: dependencies

#352 🔥 Remove homeassistant_cli
  README.md
  ssh/DOCS.md
  ssh/Dockerfile
  ssh/requirements.txt
Labels: breaking-change

#353 🔥 Remove left over hass-cli auto completion
  ssh/rootfs/root/.zshrc
Labels: maintenance
