Repository hassio-addons/addon-ssh, pull requests merged in 2022-01, with the labels that each got.

#357 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  ssh/.README.j2
  ssh/DOCS.md
Labels: maintenance

#358 ⬆️ Upgrades add-on base image to 11.0.1
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies

#359 ⬆️ Upgrades Home Assistant CLI to v4.15.1
  ssh/Dockerfile
Labels: dependencies

#363 Remove HaveIBeenPwned references
  ssh/DOCS.md
Labels: documentation

#366 Fix typo introduced in #346 causing error message
  ssh/rootfs/usr/local/bin/docker
Labels: bugfix
