Repository hassio-addons/addon-ssh, pull requests merged in 2022-06, with the labels that each got.

#412 :books: Use new My Home Assistant link format
  ssh/DOCS.md
Labels: documentation

#411 ⬆️ Upgrades Home Assistant CLI to v4.18.0
  ssh/Dockerfile
Labels: dependencies

#415 :ambulance: Fix missing nmcli
  ssh/Dockerfile
Labels: bugfix

#416 Spelling fixes
  .github/SECURITY.md
  README.md
  ssh/DOCS.md
  ssh/rootfs/etc/services.d/sshd/finish
  ssh/rootfs/etc/services.d/ttyd/finish
Labels: maintenance
