Repository hassio-addons/addon-ssh, pull requests merged in 2022-12, with the labels that each got.

#474 ⬆️ Upgrades add-on base image to 13.0.0
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies, major

#475 ⬆️ Upgrades git to 2.38.2-r0
  ssh/Dockerfile
Labels: dependencies

#469 Fix bash; use hash mark in root prompt
  ssh/rootfs/etc/profile.d/hassio.sh
Labels: bugfix
