Repository hassio-addons/addon-ssh, pull requests merged in 2022-11, with the labels that each got.

#448 ⬆️ Upgrades docker to 20.10.20-r0
  ssh/Dockerfile
Labels: dependencies

#449 ⬆️ Upgrades git to 2.36.3-r0
  ssh/Dockerfile
Labels: dependencies

#450 ⬆️ Upgrades mariadb-client to 10.6.10-r0
  ssh/Dockerfile
Labels: dependencies

#451 ⬆️ Upgrades bind-tools to 9.16.33-r0
  ssh/Dockerfile
Labels: dependencies

#453 ⬆️ Upgrades rsync to 3.2.7-r0
  ssh/Dockerfile
Labels: dependencies

#454 ⬆️ Upgrades libxml2-utils to 2.9.14-r2
  ssh/Dockerfile
Labels: dependencies

#456 ⬆️ Upgrades ttyd to 1.7.2
  ssh/Dockerfile
Labels: dependencies

#445 ✏️ Fix typo in SSH key or password missing error
  ssh/rootfs/etc/cont-init.d/ssh.sh
Labels: enhancement

#434 🪟 Set window title in bash prompt
  ssh/rootfs/etc/profile.d/hassio.sh
Labels: enhancement

#457 ⬆️ Upgrades Home Assistant CLI to v4.22.0
  ssh/Dockerfile
Labels: dependencies

#461 ⬆️ Upgrades sudo to 1.9.12-r1
  ssh/Dockerfile
Labels: dependencies

#460 🚑 Fix ha CLI autocompletion
  ssh/rootfs/root/.zshrc
Labels: bugfix

#464 ⬆️ Upgrades add-on base image to 12.2.6
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies

#462 Fix bash completion
  ssh/Dockerfile
Labels: bugfix

#465 ⬆️ Upgrades Home Assistant CLI to v4.23.0
  ssh/Dockerfile
Labels: dependencies

#467 ⬆️ Upgrades python3 to 3.10.8-r0
  ssh/Dockerfile
Labels: dependencies

#468 ⬆️ Upgrades add-on base image to 12.2.7
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies
