Repository hassio-addons/addon-ssh, pull requests merged in 2022-03, with the labels that each got.

#381 ⬆️ Upgrades bind-tools to 9.16.25-r0
  ssh/Dockerfile
Labels: dependencies

#382 ⬆️ Upgrades bluez to 5.63-r0
  ssh/Dockerfile
Labels: dependencies

#383 ⬆️ Upgrades libxml2-utils to 2.9.13-r0
  ssh/Dockerfile
Labels: dependencies

#384 ⬆️ Upgrades vim to 8.2.4173-r0
  ssh/Dockerfile
Labels: dependencies

#385 ⬆️ Upgrades zsh to 5.8.1-r0
  ssh/Dockerfile
Labels: dependencies

#386 ⬆️ Upgrades zsh-syntax-highlighting to 0.7.1-r1
  ssh/Dockerfile
Labels: dependencies

#387 ⬆️ Upgrades add-on base image to 11.1.0
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies

#388 :lock: Sign add-on with Codenotary Community Attestation Service (CAS)
  ssh/build.yaml
  ssh/config.yaml
Labels: enhancement

#390 :lock: Pass sign token to main workflow
  .github/workflows/deploy.yaml
Labels: ci

#368 Preserve the SSH_AUTH_SOCK environment variable
  ssh/rootfs/etc/sudoers.d/ssh-agent-env
Labels: enhancement
