Repository hassio-addons/addon-ssh, pull requests merged in 2022-04, with the labels that each got.

#396 📚 Add note on usernames
  ssh/DOCS.md
Labels: documentation

#397 ⬆️ Upgrades add-on base image to 11.1.2
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies

#399 ⬆️ Upgrades zlib-dev to 1.2.12-r1
  ssh/Dockerfile
Labels: dependencies

#400 ⬆️ Upgrades bind-tools to 9.16.27-r0
  ssh/Dockerfile
Labels: dependencies

#401 ⬆️ Upgrades bluez to 5.64-r0
  ssh/Dockerfile
Labels: dependencies

#402 ⬆️ Upgrades vim to 8.2.4836-r0
  ssh/Dockerfile
Labels: dependencies

#403 ⬆️ Upgrades git to 2.34.2-r0
  ssh/Dockerfile
Labels: dependencies

#404 ⬆️ Upgrades mariadb-client to 10.6.7-r0
  ssh/Dockerfile
Labels: dependencies

#405 ⬆️ Upgrades openssl to 1.1.1n-r0
  ssh/Dockerfile
Labels: dependencies

#406 :ambulance: Fix git URL for oh-my-zsh
  ssh/Dockerfile
Labels: bugfix

#407 ⬆️ Upgrades Home Assistant CLI to v4.16.1
  ssh/Dockerfile
Labels: dependencies

#408 ⬆️ Upgrades ttyd to 2b4dbac
  ssh/Dockerfile
Labels: dependencies
