Repository hassio-addons/addon-ssh, pull requests merged in 2023-12, with the labels that each got.

#649 Update SSH documentation configuration example
  ssh/DOCS.md
Labels: documentation

#656 Make vscode server data persistent
  ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
Labels: new-feature

#663 Disable the chacha20-poly1305@openssh.com cipher, CVE-2023-48795
  ssh/rootfs/etc/ssh/sshd_config
Labels: security, bugfix
