Repository hassio-addons/addon-ssh, pull requests merged in 2023-03, with the labels that each got.

#501 ⬆️ Upgrades add-on base image to 13.1.3
  ssh/Dockerfile
  ssh/build.yaml
Labels: dependencies

#513 Sync server `KexAlgorithms` with OpenSSH 9.1 and ssh-audit dev
  ssh/rootfs/etc/ssh/sshd_config
Labels: enhancement

#514 Renovate tweaks
  .github/renovate.json
Labels: maintenance

#498 Add support for VSCode Remote - SSH
  ssh/DOCS.md
  ssh/Dockerfile
Labels: new-feature

#516 Implement current ssh-audit dev client recommendations
  ssh/rootfs/etc/ssh/ssh_config
Labels: enhancement

#515 Specify server MACs and KexAlgos in terms of removals
  ssh/rootfs/etc/ssh/sshd_config
Labels: enhancement

#517 Fix broken URL
  ssh/DOCS.md
Labels: documentation

#522 :toilet: Move away from Codenotary
  ssh/build.yaml
  ssh/config.yaml
Labels: maintenance

#524 Revert ":toilet: Move away from Codenotary (#522)"
  ssh/build.yaml
  ssh/config.yaml
Labels: maintenance
