Repository hassio-addons/addon-ssh, pull requests merged in 2025-01, with the labels that each got.

#821 Update profile filename for zsh
  ssh/rootfs/etc/s6-overlay/s6-rc.d/init-ssh/run
Labels: bugfix

#782 Synchronize the Features list across all documentation
  README.md
  ssh/.README.j2
  ssh/DOCS.md
Labels: documentation

#822 :fireworks: Updates maintenance/license year to 2025
  LICENSE.md
  README.md
  ssh/.README.j2
  ssh/DOCS.md
Labels: maintenance

#826 Limit shell change to just root
  ssh/rootfs/etc/s6-overlay/s6-rc.d/init-user/run
Labels: bugfix
